[package]
name = "foxbox"
version = "0.1.0"
authors = ["fabrice <fabrice@desre.org>"]
build = "build.rs"

[dependencies]
clippy = "0.0.44"
docopt = "0.6.78"
docopt_macros = "0.6.80"
env_logger = "0.3.2"
foxbox_users = { git = "https://github.com/fxbox/users.git", rev = "d00552c" }
get_if_addrs = "0.3.1"
hyper = "0.7.2"
multicast_dns = { git = "https://github.com/fxbox/multicast-dns.git", rev = "0f211f0" }
iron = "0.2.6"
libc = "0.2.7"
log = "0.3"
mio = { git = "https://github.com/carllerche/mio.git" }
mount = "0.0.10"
openssl = "0.7.6"
openssl-sys = "0.7.6"
router = "0.1.0"
rustc-serialize = "0.3"
serde = "0.6.13"
serde_json = "0.6.0"
serde_macros = "0.6.14"
staticfile = "0.1.0"
unicase = "1.2.1"
uuid = "0.1.18"
ws = { git = "https://github.com/housleyjk/ws-rs.git", rev = "d154fc5" }

[dev-dependencies]
stainless = "0.1.4"
iron-test = "0.2.0"
